version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGODB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5